// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maeysebydtmcmsupxsgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZXlzZWJ5ZHRtY21zdXB4c2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzQyODMsImV4cCI6MjA3MTcxMDI4M30.9mL7osH_qDypO42EjlfrIIVSJDx7oSgNhzQqbq1u1wE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});